### ISSUE TITLE
Bug: The colours dont display in the picker

### ISSUE THREAD

**Issue by Ajaymamtora** [NvChad/minty#11]
One of the recent updates stopped the colours from displaying I think:
![image](https://github.com/user-attachments/assets/44eb2ae0-2290-4d99-9538-7ce754c91e4a)

This is my setup:

```lua
modules["nvchad/volt"] = {
  commit = funcs.get_commit("volt", plugins_snapshot),
  lazy = true,
}

modules["nvchad/minty"] = {
  dependencies = {
    "NvChad/volt",
  },
  commit = funcs.get_commit("minty", plugins_snapshot),
  cmd = { "Shades", "Huefy" },
  opts = { huefy = { border = true } },
}
```

I've got no errors either

**Comment by siduck** [comment]
![image](https://github.com/user-attachments/assets/69039d38-b2e4-43d2-8c92-59f03fb176db)

works fine here, please update to the latest. the  nixos users always get the weirdest issues :joy
