### ISSUE TITLE
shades doesn't really chnage the color

### ISSUE THREAD

**Issue by bassamsdata** [NvChad/minty#3]
Thank you for creating one of the coolest Neovim plugins!

I've been testing it and noticed that the Shades UI doesn't seem to change colors as expected. I've included a video to clarify what I'm referring to.

Here's a minimal repro for you:

1. `touch repro.lua`
2. Copy the repro code below into `repro.lua`
3. In the same directory as `repro.lua`, run: `nvim -u repro.lua`

**repro.lua**
```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
	spec = {
		{ "nvchad/volt", lazy = true },
		{ "nvchad/minty", lazy = true },
	},
})

-- do anything else you need to do to reproduce the issue
```

![Kapture 2024-10-03 at 22 26 08](https://github.com/user-attachments/assets/d6840d5b-0ff1-4688-8f47-1234ae695430)

Thanks again for the great work!

**Comment by siduck** [comment]
hi, click on these bars to set the new color

![image](https://github.com/user-attachments/assets/60012b8c-87a6-46aa-9080-a639cee741c3)

**Comment by bassamsdata** [comment]
oooh, thank you

**Comment by siduck** [comment]
will mention on the readme!

**Comment by siduck** [comment]
@bassamsdata  do lazy sync, the shades picker should look better now

**Comment by bassamsdata** [comment]
thank you it really do look better.
