### ISSUE TITLE
Mapping for save

### ISSUE THREAD

**Issue by niksingh710** [NvChad/minty#6]
Going to the Save button and then pressing `enter` is a bit tedious if using the whole ui from keyboard.

A Simple Keymap like `<C-cr>` to save would be nice.

**Comment by nikbrunner** [comment]
Yes I love the Plugin, but a keymap for save is the only thing missing. :)

**Comment by siduck** [comment]
<C-s>?

**Comment by siduck** [comment]
`<C-s>` is good?

**Comment by niksingh710** [comment]
> `<C-s>` is good?

yeah, it will be fine. (but i have it already mapped for writing the buffer.

adding an option so that user can override and making `<c-s>` default?

**Comment by siduck** [comment]
> (but i have it already mapped for writing the buffer.

Dont worry buffer mappings wont interfere with yours

**Comment by siduck** [comment]
```lua
opts = {
   minty = {
       mappings = (bufnr)
                 --- now user can make buf-scoped mappings here
       end
  }
}
```

thinking about something like this so in the future if more mappings are added, user can do it in the mappings function

**Comment by niksingh710** [comment]
yeah, this will be a better addition to the project as it is a future proof solution.

but why it is like `opts.minty.mappings` and not `opts.mappings` as the mapping is for the whole plugin.

**Comment by siduck** [comment]
> yeah, this will be a better addition to the project as it is a future proof solution.
> 
> but why it is like `opts.minty.mappings` and not `opts.mappings` as the mapping is for the whole plugin.

because shades and minty are both different things. shades a minimal one and minty is advanced color editor

**Comment by siduck** [comment]
done.  yall read `:h minty`
